name: Make docs

on: [push]

jobs:
  make_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: "."
          doxyfile-path: "./Doxyfile"
