name: Make docs

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: "/home/runner/work/Generic-easyC/Generic-easyC/docs/Doxyfile"
