name: Make docs

on: [push]

jobs:
  make_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: mattnotmitt/doxygen-action@v1
        with:
          doxyfile-path: "/github/workspace/docs/Doxygen"
          working-directory: "/github/workspace"
